FROM node:9-alpine
ENV PROJECT_NAME vue-koa-ts-seed
MAINTAINER <osbertngok@gmail.com>

RUN mkdir /app
WORKDIR /app
COPY ./dist /app/

COPY package.json yarn.lock /app/
RUN TMPDIR=/tmp yarn --ignore-optional && yarn cache clean


CMD node /app/app.js

EXPOSE 4000

